import Head from 'next/head'
import Navbar from '../components/navbar'
import Appointment from '../components/appointment'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import flag from '../public/flag.png'

export default function Schedule() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Billy's Autoglass Repair</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        <Appointment />
      </main>

      <footer className={styles.footer}>
          Powered by cmoorelabs
      </footer>
    </div>
  )
}
